### ISSUE TITLE
dev mode

### ISSUE THREAD

**Issue by OmegaRogue** [maritaria/terratech-mod#48]
How can i open nuterra in dev mode?

**Comment by maritaria** [comment]
There is no dev mode for Nuterra

**Comment by OmegaRogue** [comment]
But what about this? Why os it then in  the wiki?https://github.com/maritaria/nuterra/wiki

**Comment by Exund** [comment]
If he says no Dev-Mode there is No Dev-Mode

**Comment by maritaria** [comment]
That is a seperate mode for the installer to use, will be more documented later on
